function [N_DIM,N_DOMAIN,N_NODE,NODE,NODE_ID,NODE_DOMAIN,N_ELEMENT,ELEMENT,ELEMENT_ID,ELEMENT_DOMAIN,N_NODE_ELEMENT] = MESH1D(Length,n_elem)

%
N_DOMAIN = 1;
N_DIM = 1;
N_NODE = n_elem+1;
N_ELEMENT= n_elem;
NODE(1:N_NODE) = linspace(0,Length,N_ELEMENT+1);
NODE_DOMAIN(1:N_NODE) = 1;
% 
ELEMENT(1:2,1:N_ELEMENT) = [1:N_ELEMENT;2:N_ELEMENT+1];
%
NODE_ID = 1:N_NODE;
ELEMENT_ID = 1:N_ELEMENT;
ELEMENT_DOMAIN(1,1:N_ELEMENT) = 1;
ELEMENT_DOMAIN(2,1:N_ELEMENT) = 0;
ELEMENT_DOMAIN(3,1:N_ELEMENT) = 1;

N_NODE_ELEMENT(1:N_ELEMENT) = 2;

% boundaries 1 (x=0) and 2 (x=L) 
ELEMENT(1,N_ELEMENT+1) = 1;
ELEMENT(1,N_ELEMENT+2) = N_NODE;
N_NODE_ELEMENT(N_ELEMENT+1:N_ELEMENT+2) = 1;
ELEMENT_DOMAIN(1,N_ELEMENT+1:N_ELEMENT+2) = 1;
ELEMENT_DOMAIN(2,N_ELEMENT+1:N_ELEMENT+2) = 1;
ELEMENT_DOMAIN(3,N_ELEMENT+1) = 1;
ELEMENT_DOMAIN(3,N_ELEMENT+2) = 2;
%
N_ELEMENT = N_ELEMENT + 2;

